library(DBI)
library(RMySQL)
as=dbDriver("MySQL")
ash=dbConnect(as,user = "root",dbname = "emp_dept" ,host = "localhost")
a=dbListTables(ash)
print(a)
query= ("SELECT * From Employee")
r=dbGetQuery(ash,query)
print(r)
