age<-c(20,20,20,20,20,21,21,21,22,22,22,22,23,23,23)
print(median(age))
a=median(age[age<22])
print(paste("median of all students under the age of 22 is :",a))
print(paste("mean of all students age is :",mean(age)))
x=table(age)
print(x)
mode<-which(x==max(x))
print(paste("mode is:",mode))
age<-c(age,23,23)
print(median(age))
y=table(age)
print(y)
mode<-which(y==max(y))
print(paste("mode is:",mode))
print(paste("mean of all students age is :",mean(age)))